project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "ğŸ’¡ğŸ½ğŸğŸŒ± UFIT ğŸŒ±ğŸğŸ½ğŸ’¡"
  page-footer: "Website made with Quarto" 

  navbar:
    right:
      - href: index.qmd
        text: Home
      - text: Research
        menu:
          - text: Focus Areas
            href: focus_areas.qmd
          - text: News and Papers
            href: news_papers.qmd
      - text: Extension
        menu:
          - text: Extension Updates
            href: ext_updates.qmd
          - text: Participatory Research
            href: ofr.qmd
      - text: Teaching
        menu:
          - text: Student Farm
            href: stud_farm.qmd
          - text: Sustainable Vegetable Prodution
            href: svp.qmd
      - text: People
        menu:
          - text: Our People
            href: people.qmd
          - text: Job Opportunities
            href: opport.qmd
      - href: contact.qmd
        text: Contact Us

format:
  html:
    theme: custom.scss
    css: styles.css
    link-external-newwindow: true
    smooth-scroll: true
    toc: true

editor: visual
